gh actions / cmake: fix failing test on macos, t-w/ADFlib#10
This commit fixes the error that started appearing
on new MacOS images in GH actions.

Apparently, due to some unknown change, the installed binaries
had no longer the LC_RPATH set, what resulted in the error:
--------------------------------------------------------
Run examples/tests/test_examples_basic.sh bin/
  examples/tests/test_examples_basic.sh bin/
  shell: /bin/bash -e {0}
=============================================================
executing:  unadf -r examples/tests/arccsh.adf
dyld[3945]: Library not loaded: @rpath/libadf.1.dylib
  Referenced from: [...] /usr/local/bin/unadf
  Reason: no LC_RPATH's found
[...]
examples/tests/test_examples_basic.sh: line 39: [...]
Error: Process completed with exit code 134.
--------------------------------------------------------

The INSTALL_RPATH property had to be set in CMake configuration
to fix the problem. More details in the linked issue and on:
https://discourse.cmake.org/t/how-to-get-an-lc-rpath-and-rpath-prefix-on-a-dylib-on-macos/5540/7